export const user =[
    {
        id: 1,
        name: {
            firstname: "Jhaine",
            lastname: "Dalen",
        },
        course: "BS Nursing",
        year: 3,
        section: "A",
        userType: "Student",
        username: "jhaine20",
        password: "@ikawugako",
    },
    {
        id: 2,
        name: {
            firstname: "Roselle",
            lastname: "Lanson",
        },
        course: "BSIT Food Preparation",
        year: 1,
        section: "B",
        userType: "Student",
        username: "roselinda",
        password: "@lindako",
    },
    {
        id: 3,
        name: {
            firstname: "Jelly Bean",
            lastname: "Canete",
        },
        course: "BS Criminology",
        year: 1,
        section: "F",
        userType: "Student",
        username: "Bean",
        password: "@beanjelly",
    },
    {
        id: 4,
        name: {
            firstname: "Stephanie",
            lastname: "Hinlo",
        },
        course: "BSIT Food Preparation",
        year: '1',
        section: "C",
        userType: "Student",
        username: "trisha",
        password: "_trish",
    },
    {
        id: 5,
        name: {
            firstname: "Kathrine Mae",
            lastname: "Ayuban",
        },
        course: "BS Information Technology",
        year: 3,
        section: "A",
        userType: "Student",
        username: "katerinnn",
        password: "ayuban06_keem",
    },
    {
        id: 6,
        name: {
            firstname: "Catherine Leah",
            lastname: "Gabo",
        },
        course: "",
        year: '',
        section: "",
        userType: "Teacher",
        username: "@cathleah",
        password: "gabo_cathyy",
    },
    {
        id: 7,
        name: {
            firstname: "Myra",
            lastname: "Mortal",
        },
        course: "BS Information Technology",
        year: "3",
        section: "A",
        userType: "Student",
        username: "_mayeth",
        password: "#mayethgal",
    },
    {
        id: 8,
        name: {
            firstname: "Abegail",
            lastname: "Canete",
        },
        course: "BS Criminology",
        year: 1,
        section: "D",
        userType: "Student",
        username: "Mariadesu",
        password: "_gwapako",
    },
    {
        id: 9,
        name: {
            firstname: "Jerry",
            lastname: "Ale",
        },
        course: "",
        year: "",
        section: "",
        userType: "Teacher",
        username: "Ale",
        password: "#jerry",
    },
    {
        id: 10,
        name: {
            firstname: "Winzeal",
            lastname: "Agoc",
        },
        course: "",
        year: '',
        section: "",
        userType: "Teacher",
        username: "_zyl",
        password: "winzeal123",
    },
];